version: '3.8'

services:
  web:
    container_name: nebulaCore
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}

  analyzer:
    container_name: analyzer
    build:
      context: ./analyzer
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./analyzer/app:/app/app
    restart: always
