version: '3.8'

services:
  web:
    container_name: nebulaCore
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    restart: always
    environment:
      DATABASE_URL: ""
